"""empty message

Revision ID: 067e0371f4b5
Revises: 638220326c97
Create Date: 2023-11-25 23:30:58.689734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067e0371f4b5'
down_revision = '638220326c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('lastName', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')

    # ### end Alembic commands ###
