"""empty message

Revision ID: 638220326c97
Revises: 1c5d006dc519
Create Date: 2023-11-24 00:35:40.599735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638220326c97'
down_revision = '1c5d006dc519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
